language: c
compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo add-apt-repository -y ppa:bake-team/releases
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq valac libglib2.0-dev itstool debhelper pkg-config bake > /dev/null

sudo: required
dist: trusty

script:
  - bake
  
after_success:
 - echo "Nice"
