.TH BAKE 1
.SH NAME
bake \- a build system
.SH SYNOPSIS
.B bake
[
.I OPTION
] ...
.SH DESCRIPTION
.B bake
is an easy to use build system
.SH OPTIONS
.TP
.B \-\-configure
Configure build options.
.TP
.B \-\-unconfigure
Clear configuration.
.TP
.B \-\-expand
Expand current recipe and print to stdout.
.TP
.B \-\-list-targets
List available targets.
.TP
.B \-\-verbose
Show verbose output.
.TP
.B \-\-debug
Print debugging messages.
.TP
.B \-v, \-\-version
Show release version.
.TP
.B \-h, \-\-help
Show help options.
