#!/bin/sh -ev

assert_exists ()
{
    if [ ! -e $1 ]
    then
        exit 1
    fi
}

echo "package.name=test
a:
    touch a
%build: a" >> Recipe

# Check running with no arguments builds a
bake
assert_exists a
