#!/bin/sh -ev

echo "package.name=test
b: a
    cp a b
c: b
    cp b c
%build : c" >> Recipe
echo "a" >> a

# Build the result, remove the intermediate and check it rebuilds
bake
ls a b c
rm b
bake
ls a b c
