#!/bin/sh -ev

assert_exists ()
{
    if [ ! -e $1 ]
    then
        exit 1
    fi
}

echo "package.name=test
a:
    touch a" >> Recipe

# Check the rule is run and produces the output
bake a
assert_exists a
