#!/bin/sh -ev

assert_exists ()
{
    if [ ! -e $1 ]
    then
        exit 1
    fi
}

assert_is_newer ()
{
    if [ $1 -ot $2 ]
    then
        exit 1
    fi
}

echo "package.name=test
a:
    touch a
b: a
    cp a b
%build : b" >> Recipe

# Build the target
bake
assert_exists a
assert_exists b

# Wait for one second so the modification time will be older
sleep 1

# Update the input and check the output is rebuilt
touch a
bake
assert_exists a
assert_exists b
assert_is_newer b a
