#!/bin/sh -ev

assert_exists ()
{
    if [ ! -e $1 ]
    then
        exit 1
    fi
}

assert_is_newer ()
{
    if [ $1 -ot $2 ]
    then
        exit 1
    fi
}

echo "package.name=test
a:
    touch a
b: a
    cp a b" >> Recipe

# Build the target
bake b
assert_exists a
assert_exists b

# Remove the input, check output is rebuilt
rm b
bake b
assert_exists a
assert_exists b
