#!/bin/sh -ev

echo "package.name=test
b: a
    cp a b
c: b
    cp b c
%build : c" >> Recipe
echo "a" >> a

# Build the result, touch the inputs and check the output rebuilds
bake
ls a b c
bake clean
# FIXME ls a b c
