programs.eb.sources = config.vapi \
                      easy-build.vala \
                      module-bzip.vala \
                      module-desktop.vala \
                      module-dpkg.vala \
                      module-gcc.vala \
                      module-ghc.vala \
                      module-gnome.vala \
                      module-gsettings.vala \
                      module-gzip.vala \
                      module-intltool.vala \
                      module-java.vala \
                      module-man.vala \
                      module-mono.vala \
                      module-package.vala \
                      module-python.vala \
                      module-rpm.vala \
                      module-vala.vala \
                      module-xzip.vala
programs.eb.packages = glib-2.0 gio-2.0 posix
programs.eb.cflags = -DGETTEXT_PACKAGE=\"easy-build\" -DVERSION=\"0.0.4~bzr\"
